server:
  port: 9090
spring:
  datasource:
    url: ${DB_DSN}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  ai:
    mcp:
      server:
        name: webmvc-mcp-server
        version: 1.0.0
        type: SYNC
        request-timeout: 120
        instructions: >-
          Use this tool to answer any question that may benefit
          from up-to-date or domain-specific information.
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
    vectorstore:
      oracle:
        distance-type: ${DISTANCE_TYPE}
        remove-existing-vector-store-table: true
        initialize-schema: true
        index-type: ${INDEX_TYPE}
    openai:
      base-url: {OPENAI_URL}
      api-key: {OPENAI_API_KEY}
      chat:
        options:
          temperature: {OP_TEMPERATURE}
          frequencyPenalty: {OP_FREQUENCY_PENALTY}
          presencePenalty: {OP_PRESENCE_PENALTY}
          maxTokens: {OP_MAX_TOKENS}
          topP: {OP_TOP_P}
          model: ${OPENAI_CHAT_MODEL}
      embedding:
        options:
          model: ${OPENAI_EMBEDDING_MODEL}
    ollama:
      base-url: ${OLLAMA_BASE_URL}
      chat:
        options:
          top-p: {OL_TOP_P}
          presence-penalty: {OL_PRESENCE_PENALTY}
          frequency-penalty: {OL_FREQUENCY_PENALTY}
          temperature: {OL_TEMPERATURE}
          num-predict: {OL_MAX_TOKENS}
          model: ${OLLAMA_CHAT_MODEL}
      embedding:
        options:
          model: ${OLLAMA_EMBEDDING_MODEL}
aims:
  sys_instr: ${SYS_INSTR}
  vectortable:
    name: ${VECTOR_STORE}
    user: ${USER_TABLE}
  rag_params:
    search_type: Similarity
    top_k: ${TOP_K}
