## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent

{{- if .Values.server.oci_config }}
{{- /* Determine the ConfigMap name to use or create */ -}}
{{- $configMapName := .Values.server.oci_config.configMapName | default (printf "%s-oci-config" .Release.Name) }}

{{- /* Check if the ConfigMap already exists */ -}}
{{- $configMapExists := lookup "v1" "ConfigMap" .Release.Namespace $configMapName }}

{{- /* Only create ConfigMap if it doesn't exist */ -}}
{{- if not $configMapExists }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapName }}
  labels:
    app.kubernetes.io/component: server
    {{- include "global.labels" . | nindent 4 }}
data:
  {{- with .Values.server.oci_config }}
    {{- if .tenancy }}
  tenancy: {{ .tenancy | quote }}
    {{- end }}
    {{- if .user }}
  user: {{ .user | quote }}
    {{- end }}
    {{- if .fingerprint }}
  fingerprint: {{ .fingerprint | quote }}
    {{- end }}
    {{- if .region }}
  region: {{ .region | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end -}}