## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent sidb

apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.serviceName" . }}
  labels:
    app.kubernetes.io/component: server
    {{- include "global.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.server.service.port | default 8000 }}
      targetPort: 8000
  selector:
    app.kubernetes.io/component: server
    {{- include "global.selectorLabels" . | nindent 4 }}

---
{{- if eq (include "server.database.isContainerDB" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ include "server.database.dbName" . }}-1521
  labels:
    app.kubernetes.io/component: database
    {{- include "global.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: oracle-db
      protocol: TCP
      port: 1521
      targetPort: 1521
  selector:
    app.kubernetes.io/component: database
    {{- include "global.selectorLabels" . | nindent 4 }}
{{- end }}
