## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent

{{- if .Values.client.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "global.fullname" . }}-st-config
  labels:
    app.kubernetes.io/component: client
    {{- include "global.labels" . | nindent 4}}
data:
  config.toml: |
    [global]
    disableWidgetStateDuplicationWarning = true

    [browser]
    gatherUsageStats = false
    serverAddress = "0.0.0.0"

    [server]
    port = "8501"
    cookieSecret = "{{ randAlphaNum 32 | b64enc }}"
    headless = true
    fileWatcherType = "none"
    {{- $path := include "global.getPath" . | trimSuffix "/" }}
    {{- if ne $path "" }}
    baseUrlPath = {{ $path | quote }}
    {{- end }}

    [client]
    toolbarMode = "minimal"
{{ end -}}