## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent tolerations streamlit snakecase

{{- if .Values.client.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "global.fullname" . }}-client
  labels:
    app.kubernetes.io/component: client
    {{- include "global.labels" . | nindent 4}}
spec:
  {{- if not .Values.client.autoscaling.enabled }}
  replicas: {{ .Values.client.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: client
      {{- include "global.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.client.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: client
        {{- include "global.labels" . | nindent 8 }}
        {{- with .Values.client.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        fsGroup: 10001
      {{- with .Values.client.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy | default "IfNotPresent" }}
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          env:
            - name: API_SERVER_URL
              value: {{ include "server.serviceUrl" . }}
            - name: API_SERVER_PORT
              value: {{ .Values.server.service.port | default 8000 | quote }}
            - name: API_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "global.apiSecretName" . }}
                  key: {{ include "global.apiSecretKey" . }}
            {{- range $key, $value := .Values.client.features }}
            {{- if $value }}
            - name: {{ snakecase $key | upper }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          ports:
            - name: client-port
              containerPort: 8501
              protocol: TCP
          {{- if .Values.client.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ include "global.getPath" . }}ping
              port: client-port
            {{- with omit .Values.client.livenessProbe "enabled" }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.client.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ include "global.getPath" . }}ping
              port: client-port
            {{- with omit .Values.client.readinessProbe "enabled" }}
               {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.client.resources }}
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: "/app/tmp"
            - name: streamlit-config
              mountPath: /app/.streamlit
          {{- with .Values.client.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: streamlit-config
          configMap:
            name: {{ include "global.fullname" . }}-st-config
      {{- with .Values.client.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end -}}