## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent

{{- if and .Values.client.enabled .Values.client.ingress.enabled -}}
{{- if and .Values.client.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.client.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.client.ingress.annotations "kubernetes.io/ingress.class" .Values.client.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "global.fullname" . }}-client-http
  labels:
    app.kubernetes.io/component: client
    {{- include "global.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    {{- with .Values.client.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.client.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.client.ingress.className }}
  {{- end }}
  {{- if .Values.client.ingress.tls }}
  tls:
    {{- range .Values.client.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: {{ include "global.getPath" . | trimSuffix "/" | default "/" }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "global.fullname" . }}-client-http
                port:
                  number: {{ .Values.client.service.port }}
              {{- else }}
              serviceName: {{ include "global.fullname" . }}-client-http
              servicePort: {{ .Values.client.service.port }}
              {{- end }}
{{- end }}