# Copyright (c) 2024, 2026, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent

# ADB Wallet Password Secret
# Skip creating this secret if using existing ADB secrets (e.g., from obaas chart)
{{- if .Values.server.database }}
{{- if eq (include "server.database.isADBS" .) "true" }}
{{- if ne (include "server.database.useExistingAdbSecrets" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "server.database.adbWalletPassSecret" . }}
  labels:
    app.kubernetes.io/component: database
    {{- include "global.labels" . | nindent 4 }}
stringData:
  {{ include "server.database.adbWalletPassSecretKey" . }}: {{ include "server.randomPassword" . | quote }}
{{- end }}
{{- end }}
{{- end }}
