blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Documentation
    url: https://oracle.github.io/ai-optimizer/
    about: Learn more about how to use the AI Optimizer and Toolkit
  - name: â“ Anything else?
    url: https://oracledevs.slack.com/archives/C089NPXG8AU
    about: Ask questions or provide feedback on the AI Optimizer and Toolkit community Slack channel