ollama:
  gpu:
    enabled: true
    type: 'nvidia'
    number: 1
  models:
    - qwen2.5:7b
    - llama3.2
    - mxbai-embed-large
    - nomic-embed-text
nodeSelector:
  node.kubernetes.io/instance-type: VM.GPU.A10.1
