## Copyright (c) 2024, 2026, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
[global]
disableWidgetStateDuplicationWarning = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[server]
headless = true

[client]
toolbarMode = "minimal"