apiVersion: v2
name: ai-optimizer
description: A Helm chart Oracle AI Optimizer and Toolkit
version: 1.1.0
appVersion: "1.1.0"
type: application
home: https://github.com/oracle-samples/ai-optimizer
sources:
  - https://github.com/oracle-samples/ai-optimizer
icon: https://github.com/oracle-samples/ai-optimizer/blob/main/src/client/media/logo.png
maintainers:
  - name: Oracle
    email: obaas_ww@oracle.com
    url: https://github.com/oracle-samples/ai-optimizer
